CREATE TABLE categories(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    name VARCHAR(128) UNIQUE NOT NULL
);